### ISSUE TITLE
Top-menubar causes problems with too many application groups

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/django-admin-index#13]
A couple of possible solutions to this (either collapsing the menu-bar with 12+ items, or placing it vertically on the right side of the screen, or fixing the bar with 2-3 rows, or buying ultra-wide monitors), but for now this isn't viable for projects like AFS with a lot of application groups:

![screenshot_2019-03-05_12-32-33](https://user-images.githubusercontent.com/226839/53802924-6e748700-3f43-11e9-9758-a6e71c49ccd9.png)

**Comment by alextreme** [comment]
aside: the horizontal white line was due to an old version of the admin-index styling, so you can ignore that bit in the screenshot.

**Comment by joeribekker** [comment]
The idea of django-admin-index is to clean up the admin by having fewer groups :)
