### ISSUE TITLE
Raw HTML sections?

### ISSUE THREAD

**Issue by frnhr** [maykinmedia/django-admin-index#15]
Any interest in a PR that adds custom HTML sections to the App Links?

![Site_administration___urbandanish_solutions](https://user-images.githubusercontent.com/1173748/55662116-1adead00-5811-11e9-8aab-5d846007395f.jpg)

Configured with some changes in the inlines:

![Change_application_group___urbandanish_solutions](https://user-images.githubusercontent.com/1173748/55662175-90e31400-5811-11e9-9d31-0cb4e19dabe4.jpg)

**Comment by joeribekker** [comment]
Hi @frnhr! Sorry for the long wait.

Seems useful, although I don't really like raw HTML. Also, what would 2 of these do?

It would be nice to have descriptions below the AppGroup headings, but that would be more suited as a field in the AppGroup model don't you think?

**Comment by joeribekker** [comment]
It's not a feature I want to include but thanks for the contribution!
