### ISSUE TITLE
error helpers.py line 342

### ISSUE THREAD

**Issue by dimkoug** [maykinmedia/django-admin-index#2]
AttributeError: 'module' object has no attribute 'commit_on_success'

**Comment by JostCrow** [comment]
Can you please provide some extra information? Maybee a little bit of the error log or the settings that are used?

**Comment by dimkoug** [comment]
i created a virtuaenv with python3 and i installed django when i run the example project  the error i posted show. i didn't set up extra settings only the default

**Comment by JostCrow** [comment]
What I did was
```
virtualenv --python python3 env3
source ./env3/bin/activate
pip install django
pip install django-ordered-model
python manage.py check
python manage.py runserver
```

For me this worked.
python==3.6.3
django==1.11.7
django-ordered-models==1.4.3
django-admin-index==0.10.0 (current master not released yet)
ubuntu==17.10

Can you also list all the versions that I listed + os?

**Comment by dimkoug** [comment]
os : ubuntu 16.04 
python 3.5.2  default python3 for ubuntu 16.04
packages : 
Django==1.11.7
django-ordered-model==1.4.3
pytz==2017.3

same error occured

**Comment by dimkoug** [comment]
File "/home/dimitris/django-admin-tabs/example_project/example_admintabs_project/example_app/admin.py", line 6, in <module>
    from admin_tabs.helpers import TabbedModelAdmin, TabbedPageConfig, Config
  File "/home/dimitris/django-admin-tabs/example_project/admin_tabs/helpers.py", line 306, in <module>
    class TabbedModelAdmin(ModelAdmin):
  File "/home/dimitris/django-admin-tabs/example_project/admin_tabs/helpers.py", line 342, in TabbedModelAdmin

**Comment by JostCrow** [comment]
I also tried it on the os and with the versions you listed and it all seems to work. 

It looks like you have the wrong package. If I am looking at your path it says django-admin-tabs and this is django-admin-index. Maybe that could be the problem. 

here is a link to django admin tabs. https://github.com/liberation/django-admin-tabs
Maybe you can list the error there.

If not feel free to reopen this issue.
