### ISSUE TITLE
mobile menu css

### ISSUE THREAD

**Issue by ghost** [maykinmedia/django-admin-index#22]
Hi,

In mobile mode, the menu drop items is hiding behind menu item, see attached.

This issue could potentially be fixed by adding a **z-index: 100** to **class: dropdown-menu__drop** in **admin-index.css** file

Could anyone add this into the repo?

Or alternatively could anyone show us how to properly overriding the css in my django project without touching the existing css?

Thanks!

![issue](https://user-images.githubusercontent.com/9276234/69765752-59264380-11c9-11ea-85ef-8cbdcc814160.png)

**Comment by sergei-maertens** [comment]
Fixed in 44e697dc3ff77402324ea50407285be2f58dbd98, for further improvements there's still #23
