### ISSUE TITLE
False positive warning "You are missing 'django.contrib.admin' in your INSTALLED_APPS."

### ISSUE THREAD

**Issue by AndreyMZ** [maykinmedia/django-admin-index#33]
### Steps to reproduce

1. Create custom admin site and app:

    `myproject/apps/admin/sites.py`:
    ~~~py
    from django.contrib import admin

    class MyAdminSite(admin.AdminSite):
        pass
    ~~~
    
    `myproject/apps/admin/apps.py`:
    ~~~py
    from django.contrib.admin.apps import AdminConfig

    class MyAdminConfig(AdminConfig):
        default_site = 'myproject.apps.admin.sites.MyAdminSite'
    ~~~

2. Register it:

    `myproject/settings.py`:
    ~~~py
    # ...
    INSTALLED_APPS = [
        'django_admin_index',
        'ordered_model',
        'myproject.apps.admin.apps.MyAdminConfig',
        # ...
    ]
    # ...
    ~~~
    
3. Run the project.

### Actual result

>     WARNINGS:
>     ?: You are missing 'django.contrib.admin' in your INSTALLED_APPS.

### Expected result

No warnings.

**Comment by sergei-maertens** [comment]
Check should be `apps.is_installed("django.contrib.admin")` probably

**Comment by merwok** [comment]
@joeribekker does #40 work when a _custom_ admin AppConfig is used, as in the OP here?

**Comment by joeribekker** [comment]
@merwok Yes, inheriting from the Django Admin AppConfig, as done in the OP, registers the `django.contrib.admin` app as installed.
