### ISSUE TITLE
Crash when no view/edit permissions for a model are set up

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/django-admin-index#34]
In https://github.com/maykinmedia/django-admin-index/blob/7577cba087865027d125487f12e18f24fea2f6d4/django_admin_index/models.py#L36 a `TypeError` occurs if the user does not have view/edit permissions (but they have add permission, for example), because the `admin_url` key is `None`

**Comment by joeribekker** [comment]
Fixed in #36
