### ISSUE TITLE
admin-index.css contains conflict markers in version 1.4.0

### ISSUE THREAD

**Issue by pneudecorb** [maykinmedia/django-admin-index#46]
The version of admin-index.css on master contains conflict markers.  This problem exists on the deployed version of django-admin-index (currently 1.4.0).

Also using this version of the app generates errors in the browsers cannot load admin-index.css.map because that file does not exist in the deployed version 1.4.0

**Comment by joeribekker** [comment]
I think this as fixed, please double check @dariomory
