### ISSUE TITLE
Is possible to add the dashboard_app_list to custom base.html?

### ISSUE THREAD

**Issue by andriansandi** [maykinmedia/django-admin-index#48]
I'm relatively new to django, and i'm like to use your library. Is possible to add dashboard_app_list or your template tags to my own base.html?

Thanks

**Comment by sergei-maertens** [comment]
Sure- you can use the template tags in your own templates by using `{% load django_admin_index %}` and then they are available. See the relevant Django documentation: https://docs.djangoproject.com/en/2.2/ref/templates/language/#custom-tag-and-filter-libraries

**Comment by joeribekker** [comment]
Closing because the question has been answered.
