### ISSUE TITLE
Search bar seems to push everything to the right, causing horizontal scrolling

### ISSUE THREAD

**Issue by GraysonCAdams** [maykinmedia/django-admin-index#66]
Hello, I love the ability to group models together, which is really what I am using this for.

However, I noticed unfortunately that the left search bar in the backend takes up a large portion of the view, and pushing the data and filter sidebar off to the right, as seen below...

<img width="1512" alt="Screen Shot 2022-02-09 at 5 03 15 PM" src="https://user-images.githubusercontent.com/51373669/153298049-2a7359b8-7b48-480b-9e97-a983135f2a22.png">

```
Django==3.2.7
django-admin-index==1.5.0
```

Is there a solution for this?

If I set my zoom to 100% on a Macbook Pro 14", about 20-30% of the content is tucked away into an overflow where I must horizontally scroll rightward to find.

**Comment by joeribekker** [comment]
I suspect this will be fixed in the upcomming 1.6 version, since that will include Django 3.2 support.

**Comment by sergei-maertens** [comment]
Didn't see this anymore when working on 1.6 version or further improvements in #71, so closing this.
