### ISSUE TITLE
"No permissions to change things" if you're not a superuser

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/django-admin-index#9]
If you're not a super user and no application groups are created, BUT you did configure permissions (via groups) on the user, then the user doesn't see anything. The default list should show here instead.

Source issue: https://github.com/VNG-Realisatie/gemma-zaken/issues/487

**Comment by joeribekker** [comment]
Fixed in 1.2.0

See: https://github.com/maykinmedia/django-admin-index/commit/d685d2f46c4d4615d6e556dc85683a0202309fb7#diff-40e44eaaf0e41ba7143e534e34ae9b0a
